const fieldsMap = [{
	title: '创建时间',
	field: 'create_time',
	tooltip: '',
	formatter: '',
}, {
	title: '原生应用包名',
	field: 'package_name',
	formatter: '',
}, {
	title: '用户端上报的应用版本号',
	field: 'version',
	formatter: '',
	tooltip: 'manifest.json中的versionName的值',
}, {
	title: '平台',
	field: 'platform',
	formatter: '',
	tooltip: '用户端上报的平台code',
}, {
	title: '渠道',
	field: 'channel',
	formatter: '',
	tooltip: '用户端上报的渠道code场景值',
}, {
	title: '基础库版本号',
	field: 'sdk_version',
	formatter: '',
	tooltip: '',
}, {
	title: '设备标识',
	field: 'device_id',
	formatter: '',
	tooltip: '客户端携带的设备标识',
}, {
	title: '设备网络型号',
	field: 'device_net',
	formatter: '',
	tooltip: '设备网络型号wifi\/3G\/4G\/',
}, {
	title: '系统版本',
	field: 'device_os',
	formatter: '',
	tooltip: 'iOS平台为系统版本号，如15.1；Android平台为API等级，如30',
}, {
	title: '系统版本名称',
	field: 'device_os_version',
	formatter: '',
	tooltip: 'iOS平台与os字段一致；Android平台为版本名称，如5.1.1',
}, {
	title: '设备供应商',
	field: 'device_vendor',
	formatter: '',
	tooltip: '',
}, {
	title: '设备型号',
	field: 'device_model',
	formatter: '',
	tooltip: '',
}, {
	title: '是否root',
	field: 'device_is_root',
	formatter: '',
	tooltip: '1表示root；0表示未root',
}, {
	title: '系统名称',
	field: 'device_os_name',
	formatter: '',
	tooltip: '用于区别Android和鸿蒙，仅Android支持'
}, {
	title: '设备电池电量',
	field: 'device_batt_level',
	formatter: '',
	tooltip: '取值范围0-100，仅Android支持'
}, {
	title: '电池温度',
	field: 'device_batt_temp',
	formatter: '',
	tooltip: '仅Android支持'
}, {
	title: '系统已使用内存',
	field: 'device_memory_use_size',
	formatter: '',
	tooltip: '单位为Byte，仅Android支持'
}, {
	title: '系统总内存',
	field: 'device_memory_total_size',
	formatter: '',
	tooltip: '单位为Byte，仅Android支持'
}, {
	title: '系统磁盘已使用大小',
	field: 'device_disk_use_size',
	formatter: '',
	tooltip: '单位为Byte，仅Android支持'
}, {
	title: '系统磁盘总大小',
	field: 'device_disk_total_size',
	formatter: '',
	tooltip: '单位为Byte，仅Android支持'
}, {
	title: '设备支持的CPU架构',
	field: 'device_abis',
	formatter: '',
	tooltip: '多个使用,分割，如arm64-v8a,armeabi-v7a,armeabi，仅Android支持'
}, {
	title: '运行的app个数',
	field: 'app_count',
	formatter: '',
	tooltip: '包括运行的uni小程序数目，独立App时值为1'
}, {
	title: 'APP使用的内存量',
	field: 'app_use_memory_size',
	formatter: '',
	tooltip: '单位为Byte'
}, {
	title: '运行应用的个数',
	field: 'app_count',
	formatter: ''
}, {
	title: '打开 Webview 的个数',
	field: 'app_webview_count',
	formatter: ''
}, {
	title: 'APP使用时长',
	field: 'app_use_duration',
	formatter: '',
	tooltip: '单位为s'
}, {
	title: '是否前台运行',
	field: 'app_run_fore',
	formatter: '',
	tooltip: '1表示前台运行，0表示后台运行'
}, {
	title: '原生应用版本名称',
	field: 'package_version',
	formatter: '',
	tooltip: 'Android的apk版本名称；iOS的ipa版本名称'
}, {
	title: 'APP使用的内存量',
	field: 'app_use_memory_size',
	formatter: '',
	tooltip: '单位为Byte'
}, {
	title: '页面url',
	field: 'page_url',
	formatter: '',
}, {
	title: '错误信息',
	field: 'error_msg',
	formatter: '',
}]

const popupFieldsMap = [{
	title: '创建时间',
	field: 'create_time',
	formatter: '',
}, {
	title: '客户端 user-agent 信息',
	field: 'ua',
	formatter: '',
}, {
	title: '服务空间编号',
	field: 'space_id',
	formatter: '',
}, {
	title: '服务空间提供商',
	field: 'space_provider',
	formatter: '',
}, {
	title: '错误信息',
	field: 'error_msg',
	formatter: '',
}]

export {
	fieldsMap,
	popupFieldsMap,
}
