export default [{
	title: '受访页',
	field: 'url',
}, {
	title: '页面名称',
	field: 'title',
}, {
	title: '访问人数',
	field: 'num_visitor',
	tooltip: '访问人数',
	value: 0
}, {
	title: '访问次数',
	field: 'num_visits',
	tooltip: '',
	value: 0
}, {
	title: '退出页次数',
	field: 'exit_num_visits',
	tooltip: '',
	value: 0
}, {
	title: '退出率',
	field: 'exitRate',
	computed: 'exit_num_visits/num_visits',
	formart: '%',
	tooltip: '',
	value: 0
}, {
	title: '次均停留时长',
	field: 'visitAvgTime',
	computed: 'sum_visit_length/num_visits',
	formart: ':',
	tooltip: '',
	value: 0
}, {
	title: '人均停留时长 ',
	field: 'visitorAvgTime',
	computed: 'sum_visit_length/num_visitor',
	tooltip: '',
	value: 0
}, {
	title: '分享次数',
	field: 'num_share',
	tooltip: '',
	value: 0
}]
