export default [{
	title: '受访页',
	field: 'url',
}, {
	title: '页面名称',
	field: 'title',
}, {
	title: '访问人数',
	field: 'access_users',
	tooltip: '访问人数',
	value: 0
}, {
	title: '访问次数',
	field: 'access_times',
	tooltip: '',
	value: 0
}, {
	title: '退出页次数',
	field: 'exit_times',
	tooltip: '',
	value: 0
}, {
	title: '退出率',
	field: 'exitRate',
	computed: 'exit_times/access_times',
	formatter: '%',
	tooltip: '',
	value: 0
}, {
	title: '次均停留时长',
	field: 'visitAvgTime',
	computed: 'access_time/access_times',
	formatter: ':',
	tooltip: '',
	value: 0
}, {
	title: '人均停留时长 ',
	field: 'visitorAvgTime',
	computed: 'access_time/access_users',
	formatter: ':',
	tooltip: '',
	value: 0
}, {
	title: '分享次数',
	field: 'share_count',
	tooltip: '',
	value: 0
}]
