export default [{
	value: '今天',
	contrast: '昨天'
}, {
	title: '新增用户',
	field: 'new_user_count',
	tooltip: '',
	value: 0
}, {
	title: '活跃用户',
	field: 'active_user_count',
	tooltip: '',
	value: 0
}, {
	title: '访问次数',
	field: 'page_visit_count',
	tooltip: '',
	value: 0
}, {
	title: '启动次数',
	field: 'app_launch_count',
	tooltip: '访问人数',
	value: 0
}, {
	title: '次均停留时长',
	field: 'avg_session_time',
	formatter: ':',
	tooltip: '',
	value: 0
}, {
	title: '人均停留时长 ',
	field: 'avg_user_time',
	formatter: ':',
	tooltip: '',
	value: 0
}, {
	title: '跳出率',
	field: 'bounce_rate',
	formatter: '%',
	tooltip: '',
	value: 0
}, {
	title: '总用户数',
	field: 'total_users',
	tooltip: '',
	value: 0
}]
